back-end/dao/intentdao.js, back-end/interfaces/intent-interface.js, back-end/jest.config.json, back-end/package.json, back-end/schema/intent-schema.js
=> modified jest config and removed console.log

back-end/api/controllers/transcript_controller.spec.js, back-end/api/routes/transcript_route.js, back-end/helpers/transcript_data_formatter.js, back-end/helpers/transcript_data_formatter.spec.js, back-end/package-lock.json, back-end/package.json, back-end/server.js
=> added formatter and route

.github/workflows/node.js.yml
Testing change. I'm not sure if this will work yet, but I need to merge it to see.
=> Auto testing

front-end/src/App.test.js, front-end/src/components/AnalysisPage.test.js, front-end/src/components/MainPage.jsx, front-end/src/components/MainPage.test.js, front-end/src/components/TranscriptUploadModal.jsx, front-end/src/store/switchPageSlice.test.js
Added testing for AnalysisPage and switchPageSlice. Added an additional test for MainPage to see if it properly dispatches a call to open the analysis page when analyze transcript is pressed.
N/A
run tests
See https://redux.js.org/usage/writing-tests for documentation on redux tests
=> AnalysisPage and switchPageSlice tests

back-end/api/controllers/transcript_controller.spec.js, back-end/helpers/transcript_data_formatter.spec.js
Added transcript controller tests and fixed typos in transcript data formatter
=> Transcript controller tests and Transcript Data Formatter Tests

back-end/api/controllers/transcript_controller.spec.js, back-end/helpers/transcript_data_formatter.spec.js, front-end/src/components/AnalysisPage.jsx, front-end/src/components/IntentDiagram.jsx, front-end/src/components/IntentDiagram.test.js, front-end/src/components/IntentLister.jsx, front-end/src/components/IntentLister.test.js, front-end/src/components/MainPage.jsx
I added the intent lister.
Go to the analysis page and play around with the index argument for the intent lister (making sure that as long as there is at least 1 valid intent at the index, it displays correctly).
=> Added Intent Lister

.github/workflows/node.js.yml, .github/workflows/react.js.yml
=> Separated auto-testing into 2 files

back-end/helpers/transcript_data_formatter.js, front-end/package-lock.json
=> Add comments for transcript formatter

back-end/dao/intentdao.js, back-end/helpers/transcript_data_formatter.js, back-end/helpers/transcript_data_formatter.spec.js, front-end/src/components/TranscriptUploadModal.jsx
TLDR:
These are the small changes we need to get the database interaction going.
Manually test by posting test (1).json and checking mongoDB.
Please delete the intents (drop the page) you post after the test so we don't clutter our DB with fake data.
:rocket:
=> integrated components so that POST works.

front-end/src/components/TranscriptUploadModal.jsx, front-end/src/components/TranscriptUploadModal.test.js, front-end/src/services/TranscriptAPI.js
See title
To manually test use the JSON files I sent to discord as instructed.
=> Added input validation to modal

front-end/src/components/MainPage.jsx, front-end/src/components/TranscriptUploadModal.jsx
Changed the text below our logo and added a colour to the error snackbar in the modal.
To manually test open the modal and try to upload an incompatible file. 
Please suggest any other FE changes on this PR if you have any in mind.
=> Small FE-tweaks

back-end/api/controllers/transcript_controller.js, back-end/api/controllers/transcript_controller.spec.js
renamed get method and added additional testing
=> Renaming controller and added to testing

front-end/src/components/TranscriptUploadModal.jsx, front-end/src/components/TranscriptUploadModal.test.js
Closes modal automatically after successful post to backend. Also should create a window alert after a failure.
Try to upload a transcript and modal should close automatically afterwards.
=> Updated modal to show success/failure of post

front-end/src/components/TranscriptUploadModal.jsx
Fixed window alert to catch errors properly.
=> Catch errors properly in modal

front-end/src/components/IntentLister.jsx
=> IntentLister hotfix

back-end/package.json
Quick package change for deployment
=> modified package.json

.gitignore, front-end/package-lock.json, front-end/package.json, front-end/src/services/TranscriptAPI.js
=> Deployment mods

back-end/.dockerignore, back-end/Dockerfile
=> tried to add dockerfile

back-end/Dockerfile, back-end/package.json, front-end/src/components/general/BaseButton.jsx, front-end/src/components/main-page/MainPage.jsx
Changed CSS for main page to better match figma
- Look at FE and make sure it looks nice
=> Main page styling changes

front-end/src/components/main-page/TranscriptUploadModal.test.js
😢 
Long-term, I see 2 main solutions:
1. Manually make a modal ourselves (annoying but would likely fix testing issues)
2. Accept this component will remain untestable (sad, but our coverage elsewhere is good enough that we can do this in the short term)
=> skipped flaker

front-end/src/App.test.js, front-end/src/components/analysis-page/AnalysisPage.test.js, front-end/src/components/general/Icon.test.js, front-end/src/components/main-page/MainPage.jsx, front-end/src/components/main-page/MainPage.test.js, front-end/src/components/main-page/TranscriptDescription.jsx, front-end/src/components/main-page/TranscriptDescription.test.js, front-end/src/components/main-page/TranscriptUploadModal.test.js, front-end/src/store/switchPageSlice.test.js, front-end/src/store/transcriptUploadSlice.test.js, front-end/tailwind.config.js
Do we want this file to have any tests?
=> Transcript description

front-end/src/components/main-page/TranscriptUploadModal.jsx
Checks that each intent of uploaded transcript has necessary properties project_id, trace_type, and trace_payload. Shows an error if an intent does not.
Won't be adding testing since current method is shaky.
Alter an intent to not include one of the above properties and check the results.
=> Check that each intent has necessary properties

front-end/src/components/analysis-page/IntentLister.jsx, front-end/src/components/analysis-page/IntentLister.test.js, front-end/src/store/analyzeTranscriptSlice.js, front-end/src/store/analyzeTranscriptSlice.test.js
- [x ] I have added testing to this PR
=> Save intent lister index to redux

back-end/helpers/intent_analyzer.js, back-end/helpers/intent_analyzer.spec.js, back-end/helpers/transcript_data_formatter.js, back-end/helpers/transcript_data_formatter.spec.js
Parse the displayed text to get rid of voice name and fixed issues with not replacing -DOT- with .
Upload a transcript and check that the text formatting has periods and that voice name is replaced with just the name.
=> Formatting for Display

front-end/public/index.html, front-end/src/App.jsx, front-end/src/components/analysis-page/AnalysisPage.jsx, front-end/src/components/analysis-page/IntentDiagram.jsx, front-end/src/components/analysis-page/IntentLister.jsx, front-end/src/components/analysis-page/IntentMenu.jsx, front-end/src/components/general/BaseButton.jsx, front-end/src/components/general/BaseButton.test.js, front-end/src/components/main-page/MainPage.jsx, front-end/src/components/main-page/TranscriptUploadModal.jsx
I added breakpoints and other styling changes for other screen sizes. Most notable change is a reposition the percentage of each leaf so it is fixed at the top. 
Check the netlify portal and resize ur window
Very open to design ideas :grin:
=> styling changes for other screen sizes

back-end/api/controllers/flag_controller.js, back-end/api/controllers/flag_controller.spec copy.js, back-end/api/routes/flag_route.js, back-end/helpers/intent_analyzer.js, back-end/helpers/put_flag_interactor.js, back-end/helpers/put_flag_interactor.spec.js, back-end/helpers/test-helpers/testIntentFactory.js, back-end/interfaces/input-boundary-interface.js, back-end/schema/intent-schema.js, back-end/server.js
=> Added flag use case

examples/homeRepoBFSale.json
New Branch because Git is being fussy
=> Full Transcript So Far Black Friday Sale

back-end/api/controllers/flag_controller.js, back-end/api/controllers/star_controller.js, back-end/api/controllers/star_controller.spec.js, front-end/src/services/FlagAPI.js
The filtering was not working with the questions that had DOT in them. Quick fix
=> Replacing DOTs in questions for flag/star

front-end/src/components/analysis-page/AnalysisPage.jsx, front-end/src/components/analysis-page/IntentDiagram.jsx, front-end/src/components/analysis-page/IntentDiagram.test.js
Fixed the formatting on intent diagram! Please QA and let me know if it works nicely on your screen aspect ratio!
=> updated intent diagram

back-end/helpers/get/transcript_data_grouper.js, back-end/helpers/get/transcript_data_grouper.spec.js, front-end/src/components/analysis-page/IntentDiagram.jsx, front-end/src/components/analysis-page/IntentDiagram.test.js, front-end/src/components/analysis-page/IntentLister.jsx, front-end/src/components/analysis-page/IntentLister.test.js, front-end/src/services/FlagAPI.js, front-end/src/services/FlagAPI.test.js, front-end/src/services/StarAPI.js, front-end/src/services/StarAPI.test.js
Some replaceAll statements were still missing + we were not tracking previousIntents well.
Note: this PR also fixes starring/flagging
Try it with lkdsf9
=> Merge tweak

front-end/src/components/main-page/MainPage.jsx, front-end/src/components/main-page/MainPage.test.js
=> Update projectId when already analyzed

front-end/src/components/analysis-page/IntentLister.jsx, front-end/src/components/main-page/MainPage.jsx
Fixes #118 by adding additional aria attributes for a11y based on these articles:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-keyshortcuts
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-required
Not sure how to QA the attributes themselves, but quickly check that everything else is functioning as required. There are no logic changes.
=> added new aria attributes
